@startuml 1
skinparam linetype ortho
Llibre "1" *-d- "1..*" Part
Part "1" *-l- "1..*" Capítol
Capítol "1" *-u- "1..*" Secció
@enduml

@startuml 2
skinparam linetype ortho
class Llibre {
	String editor
	Date data
	int ISBN
}
class Part {
	String títol
	int número
}
class Capítol {
	String títol
	int número
	String resum
}
class Secció {
	String títol
	int número
}

Llibre "1" *-d- "1..*" Part
Part "1" *-l- "1..*" Capítol
Capítol "1" *-u- "1..*" Secció
@enduml

@startuml 3
skinparam linetype polyline
class Llibre {
	String editor
	Date data
	int ISBN
}
class Part extends Fragment
class Capítol extends Fragment {
	String resum
}
class Secció extends Fragment 
abstract Fragment {
	String títol
	int número
}

Llibre "1" *-d- "1..*" Part
Part "1" *-l- "1..*" Capítol
Capítol "1" *-l- "1..*" Secció
@enduml

@startuml 4
skinparam linetype ortho
class Persona

Persona "1..* pare" -- "1..* fill" Persona : té 
@enduml

@startuml 5

class Feina
class Treballador
class Habilitat
class Activitat extends Feina
class Projecte extends Feina
class Experiència {
	int anys
}


Treballador "5..* Treballadors" <-- "0..1 Encarregat" Treballador : Té a càrrec
Activitat "0..1 Prèvia" --> "0..* Següent" Activitat

Treballador "0..*" -- "3..*" Habilitat : Té
(Treballador, Habilitat) .. Experiència

Habilitat -- Activitat

Projecte "1" *-- "1..*" Activitat

@enduml

@startuml 6

class Treballador
class Projecte
class Activitat
class Pla
class Calendari
class ActivitatProgramada extends Activitat {
	Date dataInici
	Date dataFinal
}
class Fita extends ActivitatProgramada
class Producte

<> diamond

Pla . diamond
Projecte "1" -- diamond 
Activitat "1..*" -- diamond 
Treballador "1..*" -- diamond 

Pla "0..*" -- "1" Treballador : Posseeix

Pla -> "1" Calendari : Té

ActivitatProgramada "0..*" -- "1" Calendari : Té

Fita "0..*" -- "0..*" Producte 
(Fita, Producte) .. Estatus : Té
@enduml

@startuml 7
class Llibre {
	int ISBN
	String títol
	String editorial
	String autor
}
class Soci {
	int id
	String nom
	String cognoms
	String correu
}
class Exemplar {
	int id
	EstatCataleg estatCataleg
	EstatPrestec estatPrestec
}
enum EstatCataleg {
	ALTA
	BAIXA
}
enum EstatPrestec {
	DISPONIBLE
	NO_DISPONIBLE
}
class Préstec {
	Date dataPréstec
	Date dataRetorn
	int renovacions
}
class DataPréstec {

}

Exemplar "1..*" -- "1" Llibre : Existeix

<> diamond 

Exemplar "1" -- diamond 
Soci "1" -- diamond
DataPréstec "1..*" -- diamond
Préstec .u. diamond : Té en préstec

@enduml